### ISSUE TITLE
Error on breaking block behind sign

### ISSUE THREAD

**Issue by MrPlantPlant** [Brianetta/StickyProtection#1]
When a block behind a sign is being broken the following error will be given:

`[16:04:11] [Server thread/ERROR]: Could not pass event BlockBreakEvent to StickyProtection v0.4.1
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[craftbukkit.jar:git-Spigot-e6f93f4-22dcde5]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit.jar:git-Spigot-e6f93f4-22dcde5]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [craftbukkit.jar:git-Spigot-e6f93f4-22dcde5]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [craftbukkit.jar:git-Spigot-e6f93f4-22dcde5]
    at net.minecraft.server.v1_9_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:292) [craftbukkit.jar:git-Spigot-e6f93f4-22dcde5]
    at net.minecraft.server.v1_9_R1.PlayerInteractManager.a(PlayerInteractManager.java:124) [craftbukkit.jar:git-Spigot-e6f93f4-22dcde5]
    at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:832) [craftbukkit.jar:git-Spigot-e6f93f4-22dcde5]
    at net.minecraft.server.v1_9_R1.PacketPlayInBlockDig.a(SourceFile:40) [craftbukkit.jar:git-Spigot-e6f93f4-22dcde5]
    at net.minecraft.server.v1_9_R1.PacketPlayInBlockDig.a(SourceFile:10) [craftbukkit.jar:git-Spigot-e6f93f4-22dcde5]
    at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit.jar:git-Spigot-e6f93f4-22dcde5]
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_91]
    at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_91]
    at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [craftbukkit.jar:git-Spigot-e6f93f4-22dcde5]
    at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [craftbukkit.jar:git-Spigot-e6f93f4-22dcde5]
    at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [craftbukkit.jar:git-Spigot-e6f93f4-22dcde5]
    at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [craftbukkit.jar:git-Spigot-e6f93f4-22dcde5]
    at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [craftbukkit.jar:git-Spigot-e6f93f4-22dcde5]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
Caused by: java.lang.ClassCastException: org.bukkit.material.Sign cannot be cast to org.bukkit.material.SimpleAttachableMaterialData
    at net.simplycrafted.StickyProtection.StickyProtection.checkProtection(StickyProtection.java:106) ~[?:?]
    at net.simplycrafted.StickyProtection.StickyProtection.onBlockBreak(StickyProtection.java:214) ~[?:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_91]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[craftbukkit.jar:git-Spigot-e6f93f4-22dcde5]
    ... 17 more`

The environment is running the following:
StickyProtection 0.4.1
StickyLocks 0.9
Spigot git-Spigot-e6f93f4-22dcde5 (MC: 1.9.2)

**Comment by Brianetta** [comment]
Thanks. Sorry it took a while to see this; I shall look into it shortly.
